-- 물건어디 관리자 기능 준비 SQL
-- Supabase Dashboard > SQL Editor에서 1회 실행하세요.

create table if not exists public.usage_events (
    id bigint generated by default as identity primary key,
    event_type text not null,
    user_id text,
    nickname text,
    group_id text,
    app_version text,
    page text,
    item_count integer default 0,
    room_count integer default 0,
    zone_count integer default 0,
    user_agent text,
    created_at timestamptz not null default now()
);

create index if not exists usage_events_created_at_idx on public.usage_events (created_at desc);
create index if not exists usage_events_user_id_idx on public.usage_events (user_id);
create index if not exists usage_events_group_id_idx on public.usage_events (group_id);

alter table public.usage_events enable row level security;

drop policy if exists "usage events insert from app" on public.usage_events;
create policy "usage events insert from app"
on public.usage_events
for insert
to anon
with check (
    event_type in (
        'visit',
        'login',
        'signup',
        'join_group',
        'create_invite',
        'support_share',
        'support_copy',
        'backup_export',
        'backup_import'
    )
);

-- 보안상 브라우저/익명 사용자에게 SELECT, UPDATE, DELETE 정책은 만들지 않습니다.
-- 조회와 전체 백업은 Supabase Edge Function에서 service role key로만 수행합니다.
